### PR TITLE
Generate component `renovate.json` in post-gen-project hook

### PR DESCRIPTION
**Pull request by simu**
We expect that writing more complex package rules as Jinja2 templates in JSON will quickly become unreadable, so we move generating the component's `renovate.json` to the template's pos-gen-project Python hook where we can generate the desired package rules and other conditional configurations more easily.

Follow-up to #101 

## Checklist

- [x] The PR has a meaningful title. It will be used to auto generate the
      changelog.
      The PR has a meaningful description that sums up the change. It will be
      linked in the changelog.
- [x] PR contains a single logical change (to build a better changelog).
- [x] Categorize the PR by adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.
- [x] Link this PR to related issues or PRs.

### CODE REVIEW

**Comment by simu** [comment]
Note that this changes the JSON layout a bit:

```diff
--- base/renovate.json	2024-06-06 13:45:07.245014870 +0200
+++ feat/renovate.json	2024-06-06 13:47:36.637434662 +0200
@@ -11,17 +11,23 @@
     "commands": [
       "make gen-golden-all"
     ],
-    "fileFilters": [ "tests/golden/**" ],
+    "fileFilters": [
+      "tests/golden/**"
+    ],
     "executionMode": "update"
   },
-  "suppressNotifications": [ "artifactErrors" ],
+  "suppressNotifications": [
+    "artifactErrors"
+  ],
   "labels": [
     "dependency"
   ],
   "separateMinorPatch": true,
   "packageRules": [
     {
-      "matchUpdateTypes": ["patch"],
+      "matchUpdateTypes": [
+        "patch"
+      ],
       "matchCurrentVersion": "!/^v?0\\./",
       "automerge": true,
       "platformAutomerge": false,
```

**Review by bastjan — APPROVED** [review]
Maybe we should move the whole `renovate.json` dict into python?

**Comment by simu** [comment]
> Maybe we should move the whole `renovate.json` dict into python?

I've considered that, but I'm not sure if having the whole `renovate.json` in the post-gen-project hook would be more or less surprising than the current mixed approach.

**Comment by simu** [comment]
follow-up: see https://github.com/projectsyn/commodore-component-template/pull/107/commits/ebd82f596a2c33f52e5c8dbd6d77dc052a9a5805 for a draft implementation which fully generates the `renovate.json` from the post-gen-project hook.

After staring at it for a bit, I  think I'll use that version (+ a note in the template repo README to reduce confusion levels if someone wants to adjust the templated `renovate.json`).

**Review by bastjan — APPROVED** [review]
i like that we now can add comments as we like 👍

**Pull request merged**
